--- #  นี้เป็นไฟล์ Kubernetes YAML ที่กำหนดค่าสำหรับการสร้างและรันพื้นที่เก็บแบบถาวร (PersistentVolume) และเครื่องที่เชื่อมต่อกับพื้นที่เก็บแบบถาวร 
apiVersion: v1 # ระบุ Version
kind: PersistentVolume
metadata:
  name: mysql-pv-volume 
  labels:
    type: local
spec:
  storageClassName: manual # ระบุชื่อของคลาสเก็บข้อมูล (StorageClass) เป็น "manual"
  capacity: # ระบุความจุของ PersistentVolume เป็น 1 กิกะไบต์
    storage: 1Gi
  accessModes: # ระบุโหมดการเข้าถึงเป็น ReadWriteOnce.
    - ReadWriteOnce
  hostPath: # ระบุว่าข้อมูลจะถูกเก็บบนเครื่องโฮสต์ที่มีเส้นทางเป็น "/mysql"
    path: "/mysql"
  persistentVolumeReclaimPolicy: Recycle # ระบุว่าเมื่อ PersistentVolume ถูกปลดทิ้ง (decommission) ข้อมูลในพื้นที่จะถูกล้างใหม่ (recycle)
---
apiVersion: v1 # ระบุ Version
kind: PersistentVolumeClaim # ที่จะเชื่อมต่อกับ PersistentVolume เพื่อใช้สำหรับ MySQL
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual # ระบุชื่อของคลาสเก็บข้อมูล (StorageClass) เป็น "manual".
  accessModes:
    - ReadWriteOnce # ระบุโหมดการเข้าถึงเป็น ReadWriteOnce
  resources: # ระบุการร้องขอการใช้พื้นที่เก็บข้อมูลขนาด 1 กิกะไบต์
    requests:
      storage: 1Gi
---
apiVersion: v1 # ระบุ Version
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress-mysql
spec:
  ports: #ระบุ port
  - port: 3306
    targetPort: 3306      
  selector:
    app: wordpress-mysql
---
apiVersion: apps/v1 # ระบุ Version
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: wordpress_db
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql 
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim # adsad
